export const FETCH_PROFILES = 'FETCH_PROFILES';
export const FETCH_PROFILES_SUCCESS = 'FETCH_PROFILES_SUCCESS';
export const FETCH_PROFILES_FAILURE = 'FETCH_PROFILES_FAILURE';

export const FETCH_PROFILES_BY_SEARCH = 'FETCH_PROFILES_BY_SEARCH';
export const FETCH_PROFILES_BY_SEARCH_SUCCESS =
  'FETCH_PROFILES_BY_SEARCH_SUCCESS';
export const FETCH_PROFILES_BY_SEARCH_FAILURE =
  'FETCH_PROFILES_BY_SEARCH_FAILURE';

export const FETCH_MORE_PROFILES = 'FETCH_MORE_PROFILES';
export const FETCH_MORE_PROFILES_SUCCESS = 'FETCH_MORE_PROFILES_SUCCESS';
export const FETCH_MORE_PROFILES_FAILURE = 'FETCH_MORE_PROFILES_FAILURE';

export const USER_LOGIN = 'USER_LOGIN';
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';
export const USER_LOGIN_FAILURE = 'USER_LOGIN_FAILURE';

export const USER_LOGOUT = 'USER_LOGOUT';

export const CLEAR_SEARCH = 'CLEAR_SEARCH';
