export const FETCH_PROFILES = 'FETCH_PROFILES';
export const FETCH_PROFILES_SUCCESS = 'FETCH_PROFILES_SUCCESS';
export const FETCH_PROFILES_FAILURE = 'FETCH_PROFILES_FAILURE';

export const FETCH_MORE_PROFILES = 'FETCH_MORE_PROFILES';
export const FETCH_MORE_PROFILES_SUCCESS = 'FETCH_MORE_PROFILES_SUCCESS';
export const FETCH_MORE_PROFILES_FAILURE = 'FETCH_MORE_PROFILES_FAILURE';
